### ISSUE TITLE
사용가능 API 범위

### ISSUE THREAD

**Issue by Gumball12** [Naver-AI-Hackathon/AI_Burning_Day#16]
비슷한 질문이 있으나, 혼동되는 부분이 있어 이슈를 남기게 되었습니다.

타 이슈(#8, #12, #13)에서 언급하셨듯이, 그리고 [README](https://github.com/Naver-AI-Hackathon/AI_Burning_Day#%EB%AF%B8%EC%85%98)에서도 나와있듯이

**NCP _AI Service API_ 목록에 있는 API는 제외 없이 모두 사용가능하다** 고 해주셨는데

이 말이 API Gateway나 Cloud Functions와 같은 _AI Service API_ 목록에 없는 서비스의 사용이 불가능함을 의미하는지 알고 싶습니다.

\+ AI Service API를 사용하되, 타 딥러닝 모델도 함께 사용하여 서비스를 구현해도 되는건가요?

**Comment by Hackoperation** [comment]
안녕하세요.

AI Service API 목록에 있는 API는 1가지 이상만 활용한다 라는 개발조건만 충족한다면 이외에는 추가 개발제한을 두지 않습니다. 
따라서, AI Service API 외에 API 혹은 다 딥러닝 모델도 함께 사용하여 개발/구현 가능합니다 .

감사합니다

**Comment by Gumball12** [comment]
감사합니다.
