### ISSUE TITLE
API 사용 질문

### ISSUE THREAD

**Issue by blesk011** [Naver-AI-Hackathon/AI_Burning_Day#25]
네이버 클라우드 플랫폼 AI Service 외에 네이버 클라우드 플랫폼에 있는 Application Service 또는 외부 API Service를 사용할 수 있나요?

**Comment by Hackoperation** [comment]
안녕하세요. 

네이버클라우드플랫폼 AI API를 1가지 이상 꼭 활용하셔야 하며,
위 조건만 충족한다면 이외(NCP 혹은 외부) API를 활용하시는 것에 제한은 없습니다. 

감사합니다.
