### ISSUE TITLE
크레딧 관련 문의 드립니다.

### ISSUE THREAD

**Issue by notkimwol** [Naver-AI-Hackathon/AI_Burning_Day#27]
안녕하세요.
홈페이지에는 참가 신청시 크레딧을 지급한다고 적혀져 있는데, 언제쯤 크레딧이 나오는지 알 수 있을까요?

**Comment by Hackoperation** [comment]
안녕하세요. 

참가신청 혜택으로 받는 크레딧(총 30만원)은 중복 지원 등 검토를 마치고 1월 31일 전후로 지급 받으실 수 있으며 크레딧 유효기간은 1년입니다. 

감사합니다.
