### ISSUE TITLE
메인 홈페이지에 오탈자가 존재합니다.

### ISSUE THREAD

**Issue by dev-sngwn** [Naver-AI-Hackathon/AI_Burning_Day#3]
https://campaign.naver.com/aihackathon_ai_burning/

브라우저 탭에 표기되는 메인 타이틀이 <strong>NAVER AI Bruning Day 2019</strong>로 되어있습니다.

> Bruning → Burning

수정이 필요해보입니다! :)

**Comment by Hackoperation** [comment]
안녕하세요. 

앗. 알려주셔서 감사합니다~ 바로 반영할게요~

고맙습니다!
