### ISSUE TITLE
본선 참관관련 문의입니다.

### ISSUE THREAD

**Issue by zzagn** [Naver-AI-Hackathon/AI_Burning_Day#35]
안녕하세요. 창업진흥원의 최원일 주임이라고 합니다.

현재 네이버에서 진행예정인 AI 해커톤 대회와 관련하여,
본선 참관관련 기회가 있는지, 기회가 있다면, 참관 신청방법을 알고자합니다.

긍정적인 답변 부탁드리겠습니다.

감사합니다.

**Comment by Hackoperation** [comment]
안녕하세요. 담당자입니다. 
dl_naver_aihack@navercorp.com 로 연락주시면 감사하겠습니다. 

감사합니다.
