### ISSUE TITLE
중복 참가가 가능한지 알고싶습니다.

### ISSUE THREAD

**Issue by WisdomKang** [Naver-AI-Hackathon/AI_Burning_Day#39]
팀단위로 참가하고 
개인적으로 다른 참가하여 진행이 가능한지 문의 드립니다.

**Comment by Hackoperation** [comment]
안녕하세요. 

죄송하지만 중복 참여는 불가합니다. 고려하고 계신 팀 중에 한 팀만 선정하셔서 참여해주시길 부탁드릴게요~

감사합니다.
