### ISSUE TITLE
참여하지 못하게 되었을 때

### ISSUE THREAD

**Issue by geronimo03** [Naver-AI-Hackathon/AI_Burning_Day#40]
안녕하세요.. 
죄송합니다. 준비가 부족하고 일정이 맞지 않아 참가하지 못하게 되었습니다...
1월 7일 그 이유와 팀명, 개인정보를 포함한 이메일을 dl_naver_aihack@navercorp.com로 보내드렸습니다. 
하지만 확인이 어려워 다시 한 번 질문드려요. 취소하게 될 경우 이메일로 보내드리는 것이 맞나요?

**Comment by Hackoperation** [comment]
안녕하세요.

개별 메일 답변드렸습니다.^^

**Comment by geronimo03** [comment]
네 확인하고 답장 드렸어요. 

연락주셔서 감사합니다. 
갑자기 문의드려서 죄송합니다.
