### ISSUE TITLE
안녕하세요 예선에 관하여 질문드립니다.

### ISSUE THREAD

**Issue by wonderlandpark** [Naver-AI-Hackathon/AI_Burning_Day#41]
1. 예선은 오프라인에서 진행되는지 온라인에서 진행되는지 궁금합니다!
2. 신청서에 만 14세 미만 아동은 참여가 불가하다는데, 나이가 대회일 기준인가요??

**Comment by Hackoperation** [comment]
안녕하세요 

1. 예선은 온라인으로(오프라인x)진행합니다. 
2. 14세 미만 참가자는 법정대리인의 개인정보 수집 및 이용 동의가 있을 시에 참가가 가능합니다. 
(메일로 문도 문의주신 사항 확인했습니다. 관련해서는 개별 연락드리고 자세한 사항 안내드리겠습니다.)
저희 해커톤 대회의 기준은 연령에 관계없이 예선과 본선에 따른 결과물로 심사/평가합니다. 

감사합니다.

**Comment by wonderlandpark** [comment]
확인이 늦었네요 ㅜㅜ 내년에나 참가해봐야겠네요
