### ISSUE TITLE
코딩테스트 질문입니다.

### ISSUE THREAD

**Issue by ptaejoon** [Naver-AI-Hackathon/AI_Burning_Day#48]
안녕하세요. 코딩테스트 수요 조사 설문지에는 31일이 없던데 1/21~31인데 혹 31일에는 시험응시가 불가능한것인지 궁금합니다.

**Comment by Hackoperation** [comment]
안녕하세요.

31일도 가능하구요~ 수요조사 폼에는 정정 완료되었습니다~

**Comment by ptaejoon** [comment]
넵.. 답변 감사합니다. 다만 답변이 팀원들의 일정보다 조금 늦어서 어쩔 수 없이 미리 테스트를 완료했습니다. ㅜㅜ 그래도 답변
감사합니다 :)

2020년 1월 28일 (화) 오후 5:52, Hackoperation <notifications@github.com>님이 작성:
