### ISSUE TITLE
대회 일정 관련 개인적인 문의 드립니다.

### ISSUE THREAD

**Issue by roian6** [Naver-AI-Hackathon/AI_Burning_Day#5]
안녕하세요! 이번 네이버 AI 해커톤 참가를 준비하고 있는 학생입니다,

다만 대회 일정 중 부득이하게 참가가 어려운 날짜가 있어, 대회에 정상적으로 참여할 수 있을지 문의드립니다.

예선이 1/21(화) - 1/31(금) 동안 진행된다고 하셨는데, **첫날인 1/21(화) 오전**에 개인 사정으로 인해 일정 참가가 어려울 것 같습니다.

이외의 일정은 모두 정상적으로 참여가 가능합니다.

꼭 참여해보고 싶었던 대회인데, 혹시 참여에 큰 지장이 있을지 궁금합니다.

대회 운영에 수고가 많으십니다. 감사합니다.

개인적인 사항이라 `dl_naver_aihack@navercorp.com`로 문의드렸으나, 해당 메일 주소에 문제가 있어(접근 거부) 이슈로 남깁니다.

**Comment by Hackoperation** [comment]
안녕하세요. 

앗. 메일 발송에 문제가 있었군요. 죄송합니다.ㅠㅠ 현재 확인하여 정상메일인입 확인했으니, 혹 추가 문의사항이 있으시면 다시 연락주시구요.

예선 기간은 오프라인으로 진행하는 것이 아니라, Remote로 코딩테스트 진행과 기획안을 작성/제출하면 됩니다. (본선은 2박3일 오프라인 진행)
따라서, 예선 기간 중, 가능하신 일정에 진행해주시면 될 것 같고, 참여에는 문제가 없을 것 같다는 의견입니다.^^

모쪼록 궁금하신 사항에 답변이 되었길 바랍니다.
추가로 궁금한 사항이 있으시면 말씀주세요~

고맙습니다
