### ISSUE TITLE
크레딧 정보를 제출할 때, 이메일을 잘못 기재했습니다.

### ISSUE THREAD

**Issue by junhoyeo** [Naver-AI-Hackathon/AI_Burning_Day#57]
크레딧 지급 정보를 제출하는 폼에 클라우드플랫폼 가입 이메일 주소를 잘못 적었습니다. 

올바른 이메일 주소인 `hanaro0704@gmail.com`로 다시 신청했는데, 다른 문제가 있을지 몰라서 이슈 남깁니다! 😢

**Comment by Hackoperation** [comment]
안녕하세요. 

확인하여 정정 이메일로 지급드리겠습니다.

감사합니다.^^

**Comment by junhoyeo** [comment]
감사합니다 😆
