### ISSUE TITLE
기획안 디자인 양식 질문입니다.

### ISSUE THREAD

**Issue by yoon520** [Naver-AI-Hackathon/AI_Burning_Day#58]
기획안으로 만드는 피피티의 디자인 양식도 보내주신 양식 그대로 사용해야 하나요?

**Comment by Hackoperation** [comment]
안녕하세요.

양식은 제공드린 템플릿으로 활용하되 질의 내 양식은 자유롭게 작성해주시면 됩니다.

감사합니다.

**Comment by yoon520** [comment]
안녕하세요, 답변해주셔서 감사합니다.

혹시 보내주신 기획안 양식에서 Q2의 괄호 안의 "3장 전후"가 피피티의 장수를 제한한다는 의미인가요?
표지 포함해서 슬라이드를 6장 이상 작성해도 괜찮은가요?

**Comment by yoon520** [comment]
분량 다시 확인했습니다. 감사합니다.
