### ISSUE TITLE
하나 풀고 하나 에러난 상태로 끝났는데 포기할까요?

### ISSUE THREAD

**Issue by ganggaroo** [Naver-AI-Hackathon/AI_Burning_Day#61]
괴롭네요. 굳이 기획안 작성할 필요 있을까요?

**Comment by whayoung27** [comment]
안녕하세요, 

<dl_naver_aihack@navercorp.com>
위 메일로 성함과 팀명 알려 주시면 에러 사항 확인해 드리겠습니다. 

고맙습니다.

**Comment by ganggaroo** [comment]
아 시스템 적으로는 문제 없었습니다. 문제를 일으켜서 죄송합니다.
