### ISSUE TITLE
기획안 제출 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by nabi-chan** [Naver-AI-Hackathon/AI_Burning_Day#70]
안녕하세요.
기획안 제출을 위해 팀원의 정보를 입력했는데,
팀이 지원이 되었음에도 불구하고, "응모 정보를 확인할 수 없다" 는 alert창이 뜹니다.

**Comment by Hackoperation** [comment]
안녕하세요.

위 오류 관련 메일문의에 답변드린 것으로 확인되어 이슈 클로즈합니다.
추가 문의있으시면 연락주세요.

감사합니다.
운영진드림
