### ISSUE TITLE
기획안 제출 할때 동영상있는 경우

### ISSUE THREAD

**Issue by AICYJ** [Naver-AI-Hackathon/AI_Burning_Day#71]
그래서 ppt를 pdf로 떠서 제출하고 동영상은 메일로 보내 드렸습니다 
혹시 이렇게 제출해도 둘다 반영이 되는 건가요?

**Comment by Hackoperation** [comment]
안녕하세요.

메인 문의로, 답변 드린 것으로 확인되어 이슈 클로즈합니다.
추가 문의 있으시면 연락주세요.

감사합니다.
운영진드림
